### ISSUE TITLE
Documentation Images

### ISSUE THREAD

**Issue by gjmh-unikent** [unikent/kent-theme#48]
This issue is being used to keep imagery so we can reference in the wiki. Please keep this open.

**Comment by gjmh-unikent** [comment]
<img width="1143" alt="screen shot 2016-06-16 at 11 50 01" src="https://cloud.githubusercontent.com/assets/9929369/16114329/9321ff2c-33b8-11e6-8833-5622c77ad49a.png">

**Comment by gjmh-unikent** [comment]
![screen shot 2016-11-17 at 16 45 02](https://cloud.githubusercontent.com/assets/9929369/20398416/4a33526a-ace5-11e6-9033-6a1fca42ca32.png)

**Comment by ghost** [comment]
![list-card](https://cloud.githubusercontent.com/assets/4137942/20428288/234e2c7e-ad80-11e6-98ab-9ae18382ac1a.gif)

**Comment by gjmh-unikent** [comment]
![screen shot 2016-11-18 at 11 49 12](https://cloud.githubusercontent.com/assets/9929369/20429209/28da13ba-ad85-11e6-8b02-5f1065a85a38.png)
